GET http://localhost:3001/api/persons

###
GET http://localhost:3001/api/persons/oo

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{ 
  "name": "Artosyn Hellas", 
  "number": 409123456
}